version: '3.4'

services:
  migrations:
    container_name: mssql-server-in-docker
    image: mssql-server-db-img
    environment:
      SA_PASSWORD: "!aA12345"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"    
    build:
      context: .
      dockerfile: ./Dockerfile      
    ports:
      - 1433:1433
