name: Build and Test
on:
  workflow_call:

  push:
    branches: 
      - main 
      - develop
 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:       
      - main

permissions:
    contents: read 

jobs:
  build_and_test_net:
    name: Build and Test .Net App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache .NET packages    
      uses: actions/cache@v3
      id: dotnet-cache
      with:
        path: ~/.nuget/packages
        key: dotnet-packages-${{ github.repository }}
        restore-keys: dotnet-packages-${{ github.repository }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      if: steps.dotnet-cache.outputs.cache-hit != 'true'
      with:
        dotnet-version: 7.0.x
    
    - name: Build and Restore App 
      run: dotnet build  ./PixCharge.Api/PixCharge.Api.csproj --restore
      continue-on-error: false

  
  trigger_tests_sonarcloud:
    needs: build_and_test_net
    name: Triggered Build and Test
    uses: alexfariakof/Projeto-de-Bloco-Tecnologia-.NET-23E4_1/.github/workflows/test_analyse_in_Sonar_Cloud.yml@main
    secrets: inherit
