name: Test and Analysis Code In Sonar Cloud
on:
  workflow_call:

  push:
    branches: 
      - hotfix/*
      - feature/*
      - bugfix/*  

  pull_request:
    types: [opened, synchronize, reopened]
    branches:       
      - hotfix/*
      - feature/*
      - bugfix/*  

jobs:
  test_code_in_sonar_net:
    name: Test Code in Sonar Cloud
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        id: cache-sonar
        uses: actions/cache@v3        
        with:        
            path: ~\sonar\cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      
      - name: Create if not Exist Cache Sonar Packages
        if: steps.cache-sonar.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ~\sonar\cache -ItemType Directory    
        
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
            path: .\.sonar\scanner
            key: ${{ runner.os }}-sonar-scanner
            restore-keys: ${{ runner.os }}-sonar-scanner      
          
      
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path ./.sonar/scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      
      - name: Build and analyze
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |          
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"alexfariakof_Projeto-de-Bloco-Tecnologia-.NET-23E4_1" /o:"alexfariakof" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.exclusions="**/*Test*, **/.documents/**, **/Program.cs, **/*.spec.ts, **/main.ts, **/environment.*, **/*.routing.module.ts, **/*.js, **/test.ts, **/*.json, **/Dockerfile*, **/*html*, **/*.html, **/*Migrations*, **/PixCharge.Integration.Adapter*, **/Data*" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.cs.lcov.reportPaths="**/coveragereport/lcov.info" /d:sonar.typescript.opencover.reportsPaths="**/**/coverage/clover.xml" /d:sonar.typescript.lcov.reportPaths="**/**/coverage/lcov.info"
          
          # Executa Build Restore com Teste e coleta o GUID gerado          
          dotnet test ./PixCharge.Test/PixCharge.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect:"XPlat Code Coverage;Format=opencover"
            
          $projectTestPath = Get-Location
          $projectPath =  (Resolve-Path -Path ..).Path
          $sourceDirs = "$baseDirectory\PixCharge.Business;$baseDirectory\PixCharge.Domain;$baseDirectory\PixCharge.Repository;$baseDirectory\PixCharge.SPA;$projectPath\PixCharge.SPA\angularapp"
          $coverageXmlPath = Join-Path -Path (Join-Path -Path $projectTestPath -ChildPath "TestResults") -ChildPath "coveragereport"
          $filefilters = "-$projectPath\PixCharge.Infrastructure.Migrations_MsSqlServer\**;-$projectPath\PixCharge.Infrastructure.Migrations_MySqlServer\**;-$projectPath\PixCharge.Integration.Adapter\**;"

          dotnet tool install -g dotnet-reportgenerator-globaltool 
          reportgenerator -reports:$projectTestPath\coverage.cobertura.xml -targetdir:$coverageXmlPath -reporttypes:"Html;lcov;" -sourcedirs:$sourceDirs -filefilters:$filefilters

          cd PixCharge.SPA/angularapp
          npm install npm@latest > $null 2>&1
          npm install -g @angular/cli > $null 2>&1
          npm install > $null 2>&1
          npm run test:coverage
          cd ..
          cd ..

          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  
